ALTER TABLE forge_projects ADD COLUMN owner_id text NOT NULL DEFAULT 'local-owner', ADD COLUMN brief text NOT NULL DEFAULT '', ADD COLUMN design jsonb NOT NULL DEFAULT '{"style":"","preserve":""}', ADD COLUMN archived boolean NOT NULL DEFAULT false, ADD COLUMN starred boolean NOT NULL DEFAULT false, ADD COLUMN last_opened_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE forge_jobs ADD COLUMN owner_id text NOT NULL DEFAULT 'local-owner', ADD COLUMN idempotency_key text, ADD COLUMN base_revision text, ADD COLUMN cancelled boolean NOT NULL DEFAULT false;
ALTER TABLE forge_jobs DROP CONSTRAINT forge_jobs_kind_check;
ALTER TABLE forge_jobs ADD CONSTRAINT forge_jobs_kind_check CHECK (kind IN ('generate','edit','restore','idea','brainstorm','plan'));
ALTER TABLE forge_jobs DROP CONSTRAINT forge_jobs_status_check;
ALTER TABLE forge_jobs ADD CONSTRAINT forge_jobs_status_check CHECK (status IN ('queued','running','complete','failed','cancelled'));
CREATE UNIQUE INDEX forge_job_idempotency ON forge_jobs(owner_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX forge_projects_owner_recent ON forge_projects(owner_id,last_opened_at DESC);
CREATE INDEX forge_projects_search ON forge_projects USING gin (to_tsvector('simple',name || ' ' || brief));
CREATE TABLE forge_messages(id text PRIMARY KEY, project_id text NOT NULL REFERENCES forge_projects(id), role text NOT NULL, mode text NOT NULL, content text NOT NULL, job_id text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX forge_messages_project ON forge_messages(project_id,created_at);
CREATE TABLE forge_memberships(id text PRIMARY KEY, project_id text NOT NULL REFERENCES forge_projects(id), user_id text NOT NULL, role text NOT NULL CHECK(role IN ('viewer','commenter')), UNIQUE(project_id,user_id));
CREATE TABLE forge_comments(id text PRIMARY KEY, project_id text NOT NULL REFERENCES forge_projects(id), user_id text NOT NULL, revision_id text NOT NULL, page text NOT NULL DEFAULT '/', content text NOT NULL, resolved boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE forge_user(id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, email_verified boolean NOT NULL DEFAULT false, image text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE forge_session(id text PRIMARY KEY, expires_at timestamptz NOT NULL, token text NOT NULL UNIQUE, ip_address text, user_agent text, user_id text NOT NULL REFERENCES forge_user(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX forge_session_user ON forge_session(user_id);
CREATE TABLE forge_account(id text PRIMARY KEY, account_id text NOT NULL, provider_id text NOT NULL, user_id text NOT NULL REFERENCES forge_user(id) ON DELETE CASCADE, access_token text, refresh_token text, id_token text, access_token_expires_at timestamptz, refresh_token_expires_at timestamptz, scope text, password text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX forge_account_user ON forge_account(user_id);
CREATE TABLE forge_verification(id text PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX forge_verification_identifier ON forge_verification(identifier);
CREATE TABLE forge_beta_invites(email text PRIMARY KEY, expires_at timestamptz NOT NULL, revoked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
