import { escapeHTML, footer, topbar } from '../components/ui'

export const demoPrompt = `Your own, describe your product well.

Build a responsive personal reading tracker called Field Notes. It is for one reader who wants to organize books, record progress, and keep short notes. The main outcome is to find the next book to read and update progress without a complicated workflow.

FIRST VERSION
Create three connected views: Library, Book details, and Reading summary. Use real navigation, including a clear way back to the Library. Keep this version focused on one person using one browser. Do not add account sign-in, payments, social sharing, or external book APIs.

LIBRARY
Show book title, author, reading status, and page progress. Support adding a book, searching by title or author, and filtering by Want to read, Reading, or Finished. Include a clear Add book action and an empty state that explains how to start. A search with no matches should offer a way to clear the search. Use a compact list on small screens and a spacious grid on wider screens.

BOOK DETAILS
Allow editing the title, author, total pages, current page, reading status, and a short personal note. Require a title and author. Total pages must be a positive whole number; the current page must be between zero and the total. Explain validation errors beside the relevant field and preserve what the reader typed. Ask for confirmation before deleting a book. Cancel must leave the book unchanged.

READING SUMMARY
Calculate the number of books in each status and the total recorded pages read from the actual saved records. Do not invent statistics. If the library is empty, show a useful empty state rather than pretend activity. Explain that these figures describe the books currently in this browser.

DATA AND PERSISTENCE
Store records in browser localStorage after the application loads. Each book needs a stable ID, title, author, status, total pages, current page, note, and updated time. Data must survive navigation and a page reload. Do not read browser-only APIs during server rendering. If storage is unavailable, keep the current form usable and explain that changes cannot be saved permanently. Do not silently overwrite existing records with sample data. An optional Load sample books action may add clearly labeled fictional examples only after the reader chooses it.

VISUAL DIRECTION
Use the feeling of an independent literary journal: warm ivory surfaces, deep navy text, a restrained rust accent, generous margins, and readable typography. Give the application its own identity. Use an available serif or system-serif heading font and a clean system sans-serif for body text. Make the Library feel like a useful working tool. Do not copy Forge's interface or force an example design onto this project.

ACCESSIBILITY AND RESPONSIVENESS
Use semantic headings, labeled form controls, visible keyboard focus, and descriptive button names. Explain progress with text as well as color. All actions must work with a keyboard. If a dialog is used, give it an accessible name, keep focus inside while it is open, support Escape to cancel, and restore focus to its trigger when it closes. Check the layout at 375, 768, and 1440 pixels and at 200% zoom. Honor reduced motion.

ACCEPTANCE CHECKS
1. Add a valid book and confirm that it appears once in the Library.
2. Try an empty title, invalid page count, and current page beyond the total; each must show a clear error without losing the form.
3. Search and filter the Library, then clear those controls.
4. Update a book's progress and note, reload the page, and verify both values remain.
5. Change a reading status and confirm that the summary updates from saved data.
6. Cancel a deletion and confirm nothing changes; confirm deletion and verify that only the selected book is removed.
7. Complete the main workflow with a keyboard and check the narrow layout.

HOW TO PROCEED
Use the supported web runtime and approved dependencies. Make reasonable choices for small details. Ask a short, grouped clarification only if an essential product decision is missing. If a requirement cannot be implemented with the available capabilities, explain the limitation rather than presenting a simulated feature as complete. Finish with a concise summary of the changes, the checks actually performed, any checks I still need to run, and any known limitations.`

const chapters = [
  ['start', 'Start here'],
  ['brief', 'Describe your product'],
  ['modes', 'Choose a mode'],
  ['direction', 'Set the visual direction'],
  ['demo-prompt', 'Copy a complete prompt'],
  ['build', 'Build your first version'],
  ['check', 'Test the result'],
  ['refine', 'Make a change'],
  ['history', 'Save and recover'],
  ['projects', 'Organize your work'],
  ['availability', 'Review and publishing'],
  ['help', 'Troubleshooting'],
] as const
const chapterLinks = () =>
  chapters
    .map(
      ([id, title], i) =>
        `<a href="#guide-${id}"><span>${String(i + 1).padStart(2, '0')}</span>${title}</a>`
    )
    .join('')
const section = (id: string, number: string, title: string, body: string) =>
  `<section class="guide-section" id="guide-${id}" aria-labelledby="guide-heading-${id}"><p class="guide-kicker">${number} / FIELD GUIDE</p><h2 id="guide-heading-${id}">${title}</h2>${body}</section>`

export function documentation() {
  return `<div class="marketing">${topbar()}
<a class="skip-link" href="#guide-content">Skip to guide</a>
<main class="doc-guide" id="guide-top">
<header class="guide-hero"><p class="eyebrow">FORGE / DOCUMENTATION</p><h1>Your own.<br>Describe your product well.</h1><p class="guide-lead">A practical guide from your first sentence to a working version you can inspect, improve, and return to. Start with the outcome you want. Let the details grow from there.</p><div class="guide-hero-actions"><a class="button primary" href="#guide-demo-prompt">Read the demo prompt <span aria-hidden="true">↓</span></a><a class="guide-text-link" href="/app">Open your workspace ↗</a></div><p class="guide-edition">Product guide · Local workspace · Updated September 2026</p></header>
<div class="guide-layout"><aside class="guide-sidebar"><p class="guide-kicker">ON THIS PAGE</p><nav aria-label="Guide chapters">${chapterLinks()}</nav><a class="guide-back" href="#guide-top">Back to the beginning ↑</a></aside>
<div class="guide-reading" id="guide-content" tabindex="-1"><details class="guide-mobile-toc"><summary>On this page</summary><nav aria-label="Guide chapters on mobile">${chapterLinks()}</nav></details>
${section('start', '01', 'A clear first step.', `<p>Forge turns a written product brief into editable website or web-app source, then builds it in a separate preview environment. The current version is a local workspace. You can explore the guide and <a href="/examples">Examples</a> before connecting a model.</p><ol class="guide-steps"><li><strong>Open Home.</strong> Write what the product should do and who will use it. A starter idea fills the composer for you to review.</li><li><strong>Choose your approach.</strong> Use Build for a first application, or Plan if you want to work through the requirements first.</li><li><strong>Check readiness.</strong> Open <a href="/app/connections">Connections</a> to see the configured models. The workspace also reports whether its build worker is connected.</li><li><strong>Build, inspect, and refine.</strong> Submit once, follow the saved timeline, and test the result before asking for your next change.</li></ol><aside class="guide-note"><strong>Before you submit</strong><p>A connected model and worker are required for new requests. Requests may use your allowance, including planning requests in the current version. Reading this guide, copying the prompt, and opening a project do not start a generation.</p></aside>`)}
${section('brief', '02', 'Describe the product, not just the screen.', `<p>A useful brief tells Forge what success looks like. You do not need to choose a technical stack or a design example to begin. Use plain language and explain the decisions that affect the people using your app.</p><dl class="guide-definitions"><div><dt>Purpose and audience</dt><dd>Who is this for, and what should they be able to accomplish? “A reading tracker for one person” is more useful than “a modern dashboard.”</dd></div><div><dt>Main workflow</dt><dd>Describe the sequence: open the Library, add a book, record progress, and return later. Name the important pages and actions.</dd></div><div><dt>Information and persistence</dt><dd>List what needs to be saved. Explain whether it belongs in one browser or must be shared across accounts and devices. These are different product requirements.</dd></div><div><dt>Visual character</dt><dd>Describe typography, color, spacing, density, and navigation. Say what should be preserved when updating an existing application.</dd></div><div><dt>Boundaries and checks</dt><dd>Separate the first version from later ideas. Include examples of valid input, errors, empty states, and observable checks that prove the main workflow works.</dd></div></dl><p>For a website, focus on pages, content, navigation, and visitor actions. For a dashboard, describe records, filters, calculations, and editing. For a portal, describe account roles and which records each person may access. State those needs explicitly; a sign-in screen alone does not establish privacy.</p>`)}
${section('modes', '03', 'Choose how to move the idea forward.', `<div class="guide-table-wrap" role="region" aria-label="Creation modes" tabindex="0"><table><caption>Four modes, one project context</caption><thead><tr><th scope="col">Mode</th><th scope="col">Use it when</th><th scope="col">What to expect</th></tr></thead><tbody><tr><th scope="row">Idea</th><td>You have a starting thought.</td><td>A clearer concept, audience, and intended outcome.</td></tr><tr><th scope="row">Brainstorm</th><td>You want to explore possibilities.</td><td>Feature ideas, workflow alternatives, and tradeoffs.</td></tr><tr><th scope="row">Plan</th><td>You want a brief to review first.</td><td>Written pages, behavior, data needs, and acceptance criteria.</td></tr><tr><th scope="row">Build</th><td>You are ready for an application.</td><td>Generated files, build progress, and a preview when the build succeeds.</td></tr></tbody></table></div><p>Build is selected by default. Idea, Brainstorm, and Plan save a conversation response without starting a build sandbox. In a project, change the <strong>Mode</strong> beside the follow-up composer to continue in another mode. Review the plan and include any corrections in your next request.</p><p>A written plan is a proposal. It does not mean code was generated, features were tested, or a website was published.</p>`)}
${section('direction', '04', 'Give the application its own character.', `<p>Open <strong>Visual direction &amp; model</strong> below the composer. Leave <strong>Starting example</strong> on “Choose for me” for automatic direction, or write your preferences under <strong>Your visual direction</strong>. An example is an optional starting point.</p><p>Useful direction describes concrete choices: a dense data table with restrained color, a playful restaurant menu with large photographs, or a literary journal with generous margins. Explain what the style should help people do.</p><p>The five <a href="/examples">Examples</a> can be explored and downloaded. They do not limit your product category, layout, or colors. Your application can look different from both the examples and the Forge workspace.</p><aside class="guide-note"><strong>Working with references</strong><p>For now, describe the specific qualities you want to borrow in text. Uploading visual references and comparing generated directions are not available in this version. A pasted link alone does not guarantee that the model can open or inspect it.</p></aside>`)}
${section('demo-prompt', '05', 'One complete prompt to make your own.', `<p>This reading-tracker brief brings the pieces together: purpose, pages, data, visual direction, accessibility, and acceptance checks. Replace the product and workflow with your own. Keep the same level of clarity.</p><div class="guide-prompt-card"><div class="guide-prompt-header"><div><p class="guide-kicker">DEMO PROMPT</p><h3>Field Notes / Personal reading tracker</h3></div><button type="button" data-action="copy-guide-prompt" aria-describedby="guide-copy-status">Copy demo prompt</button></div><label class="sr-only" for="guide-demo-text">Complete demo prompt</label><textarea id="guide-demo-text" readonly rows="20" spellcheck="false">${escapeHTML(demoPrompt)}</textarea><p id="guide-copy-status" role="status" aria-live="polite">Copy this prompt, then paste it into Home and review it before submitting.</p></div><ol class="guide-steps"><li><strong>Copy and adapt.</strong> Change the name, audience, workflow, and visual direction. Remove any feature your first version does not need.</li><li><strong>Choose Plan or Build.</strong> Use Plan to discuss the brief first. Use Build to generate a candidate with your configured model.</li><li><strong>Run the acceptance checks.</strong> Treat the prompt as a specification to verify, not a promise that every requirement will pass on the first attempt.</li></ol><p class="guide-small">This is an instructional prompt, not a prebuilt or certified application. Copying it does not create a project, replace your saved composer, or consume a generation request.</p>`)}
${section('build', '06', 'Follow the work as it happens.', `<ol class="guide-steps"><li><strong>Review the composer.</strong> Confirm the product description, mode, and any visual preferences. The Model control lists the currently available choices.</li><li><strong>Select Build project.</strong> Forge saves the request and opens the project. It gives the project an initial name; use <strong>Rename</strong> in the workbench to change it.</li><li><strong>Read the timeline.</strong> It records provider activity, file validation, build output, repair attempts, and failures. Expand <strong>Build logs</strong> when you need more detail.</li><li><strong>Wait for a running preview.</strong> A candidate that cannot build does not become the working revision. Forge can attempt up to two targeted repairs for build failures.</li></ol><p>Use <strong>Stop request</strong> to ask the worker to stop the current job. Cancellation may take a moment to reach the current stage. Refreshing the project reconnects to saved progress; it should not submit another request.</p><aside class="guide-note"><strong>Local preview behavior</strong><p>The local worker runs one active preview. It may pause a working preview while it builds or opens another project. Your saved source remains in History. Use <strong>Resume preview</strong> when that action is offered.</p></aside><p>A successful build means the application compiled and started. You still need to check its behavior, data handling, and accessibility.</p>`)}
${section('check', '07', 'Test the outcome, not just the appearance.', `<p>Keep the acceptance checks from your brief beside the preview. Test the main workflow from an empty state, then repeat it with real-looking test data. Use fictional information while you are evaluating a generated application.</p><ul class="guide-checklist"><li>Follow every page link and confirm there is a clear way back.</li><li>Try the primary action and verify the resulting data or screen change.</li><li>Submit missing or invalid values. Errors should explain how to recover without losing input.</li><li>Reload the page and confirm that records or settings expected to persist are still present.</li><li>Check empty lists, searches with no results, long titles, and larger amounts of content.</li><li>Use Tab, Shift+Tab, Enter, and Escape where appropriate. Focus should remain visible and follow a logical order.</li><li>Try Desktop, Tablet, and Mobile preview widths, then check the app on an actual narrow viewport and at 200% zoom.</li></ul><p>Use <strong>Reload</strong> to refresh the preview or <strong>Open separately</strong> for more space. These actions do not publish the application. Forge’s theme controls change the workspace; the generated application follows its own design.</p><p>For the demo prompt, adding a book is only the beginning. Test page-range validation, saved notes after reload, summary calculations, and both cancellation and confirmation of deletion.</p>`)}
${section('refine', '08', 'Make a specific, reviewable change.', `<p>In <strong>Refine your app</strong>, describe the behavior to change, where it happens, what should remain, and how you will verify the result. Keep related changes together and review each result before moving on.</p><blockquote class="guide-example">In the Library, keep the existing book records and editorial style. Add sorting by title and last updated time. Preserve the search and status filters. After saving a progress update, verify that “Last updated” sorting moves that book to the top.</blockquote><p>For a bug, include what you did, what happened, and what you expected. For example, say that a reading note disappears after a reload rather than asking to “fix everything.” Do not include passwords or private service keys in a prompt.</p><h3>When you want to edit source</h3><ol class="guide-steps"><li>Open <strong>Code</strong>, find the file, and make a focused change. Protected runtime files are read-only.</li><li>Select <strong>Save &amp; rebuild</strong>. A saved edit must build before it becomes the working revision.</li><li>If a newer revision conflicts with your unsaved work, compare the latest source with your draft and copy out anything you need before choosing <strong>Discard draft and load latest</strong>.</li></ol><p>Unsaved editor buffers have local browser recovery. Keep an external copy of valuable unsaved work if browser storage is unavailable. Element selection, direct visual editing, and automatic conflict comparisons are planned; use conversational or code edits today.</p>`)}
${section('history', '09', 'Keep a way back.', `<p><strong>History</strong> lists saved working revisions. Restoring an earlier version creates another revision, preserving the history of your changes. Source restoration does not mean a public deployment has been rolled back.</p><dl class="guide-definitions"><div><dt>Restore source</dt><dd>Choose an earlier version in History. By default, current development data is preserved while the source is rebuilt.</dd></div><div><dt>Recover development data</dt><dd>The separate “Also restore the saved development data” option replaces current development records with the selected snapshot. Use it only when you intend that replacement.</dd></div><div><dt>Export source</dt><dd>Download a source package from the project toolbar. It is not a backup of live application records, browser localStorage, or service credentials.</dd></div><div><dt>Remix</dt><dd>Create an independent project from the saved source. Live database records and service credentials are excluded. Review its configuration before running it.</dd></div></dl><aside class="guide-note"><strong>Browser data is separate</strong><p>If your generated app saves information in localStorage, that information belongs to its browser origin. Source history and development-database snapshots do not back it up. Do not assume a preview address is permanent storage for important records.</p></aside>`)}
${section('projects', '10', 'Find the work you want to return to.', `<p><a href="/app">Home</a> shows recently opened projects. Open <a href="/app/projects">Projects</a> for the full library.</p><ol class="guide-steps"><li>Search by project name or brief text.</li><li>Use Owned, Shared, Starred, or Archived to narrow the list.</li><li>Sort by recently opened, recently updated, or name. Switch between Grid view and List view to suit the task.</li><li>Star a project to find it again. Archive work you want to set aside; select Archived and Unarchive to bring it back.</li></ol><p>The current allowance is five active projects, one active request per owner, and ten requests per UTC day. Planning requests and code edits also count toward the daily request allowance in this version; source restoration does not. Check the workspace allowance before starting another request. Archiving a project does not erase its source history.</p><h3>Bring in an earlier Forge brief</h3><p>Export a JSON backup from the earlier browser workspace, then open <a href="/app/settings">Settings</a> and use <strong>Import a Forge JSON backup</strong>. Imported briefs appear as archived drafts. Unarchive one when you are ready to work on it. Keep the original backup until you have checked the imported name, prompt, and example choice. Importing a brief does not generate an application.</p>`)}
${section('availability', '11', 'Know what is available before you rely on it.', `<div class="guide-availability"><div><p class="guide-kicker">AVAILABLE LOCALLY</p><h3>Build and inspect</h3><p>Prompt modes, custom written direction, optional examples, project organization, Docker previews, code editing, source history, export, and remix are available with the required local configuration.</p></div><div><p class="guide-kicker">REQUIRES CONFIGURATION</p><h3>Accounts and review</h3><p>Authentication and review permissions have a server implementation. Hosted sign-in, email delivery, dashboard connections, and private preview access still require setup and verification.</p></div><div><p class="guide-kicker">NOT AVAILABLE YET</p><h3>Visual editing and release</h3><p>Reference uploads, comparison of directions, direct visual editing, hosted previews, public publishing, custom domains, and deployment rollback remain unfinished.</p></div></div><h3>How review works when configured</h3><p>Owners use <strong>Review</strong> to add an existing verified Forge account as a viewer or commenter. Viewers have viewing permission; commenters can also leave revision comments. Owners can resolve comments and revoke access. Adding an email here does not send an invitation message, and permission alone does not make an unconfigured hosted preview available.</p><h3>A preview is not a published website</h3><p>The current local preview runs on the machine hosting Forge. A localhost link will not give someone on another computer access to your app. There is no completed publishing workflow in this version. Do not treat a build-success message, source export, or review permission as a public release.</p><p>Forge accounts and accounts inside an app you generate are separate concerns. Describe generated-app authentication, roles, and data access explicitly in your brief, then verify the implementation before trusting it with private records.</p>`)}
${section('help', '12', 'When something needs attention.', `<div class="guide-faq"><details><summary>No model is available</summary><p>Open <a href="/app/connections">Connections</a> and read the provider’s status. A workspace operator needs to configure its server credentials or local model. Keep keys out of the composer and generated source. Model availability does not by itself guarantee that generation will succeed.</p></details><details><summary>The worker is disconnected</summary><p>Your project can still contain saved source and history. New generation needs the local worker and runtime to be running. Ask the workspace operator to restore them, then check the Home status before retrying.</p></details><details><summary>A build or provider request failed</summary><p>Read the last timeline entry and expand Build logs for a build failure. Check Connections for provider errors. The last working revision should remain available. Keep the original request, identify the smallest useful correction, and retry when the service and allowance permit it.</p></details><details><summary>The preview is paused or unavailable</summary><p>The local worker may be rebuilding, recovering after a restart, or showing another project. Wait for the current request to finish. Use Resume preview if it appears. Repeatedly submitting the same prompt is not a preview-restart action.</p></details><details><summary>The daily request limit is reached</summary><p>The current allowance resets at 00:00 UTC. You can still read the documentation, inspect saved work, and organize projects. Provider limits are separate and may have their own reset times. A failed request can still count toward the Forge request allowance.</p></details><details><summary>The editor reports a newer revision</summary><p>Your unsaved draft and the saved project have diverged. Copy any local changes you want to retain before loading the latest source. Review the differences before rebuilding. Do not discard a draft just to clear the message.</p></details><details><summary>Data disappeared after a reload</summary><p>Check whether the app uses browser storage or a development database, and whether the preview address changed. Reproduce the problem with fictional data. Ask for a persistence fix with the exact steps you followed; changing the visual design will not repair missing storage behavior.</p></details></div><div class="guide-next"><p class="guide-kicker">YOUR NEXT STEP</p><h3>Start with one useful workflow.</h3><p>Write a brief you can explain, build a version you can inspect, and test the actions that matter. Keep improving from what you observe.</p><a class="button primary" href="/app">Open Home ↗</a><a class="guide-text-link" href="#guide-demo-prompt">Return to the demo prompt ↑</a></div>`)}
</div></div></main>${footer()}</div>`
}
